ARG ELASTIC_VERSION

# You can use either the image from Docker Hub or directly from Elastic

# https://www.docker.elastic.co/
#FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}

# docker hub image
FROM kibana:${ELASTIC_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
