ARG ELASTIC_VERSION

# You can use either the image from Docker Hub or directly from Elastic

# https://www.docker.elastic.co/
#FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

# docker hub image
FROM logstash:${ELASTIC_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
